version: "3.9"

services:
  database-mysql:
    image: mysql:8.0
    container_name: database-mysql-bank
    volumes:
      - database-mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
     
    networks:
      - dev_network_bank
    ports:
      - "3307:3306"

  phpmyadmin:
    depends_on:
      - database-mysql
    image: phpmyadmin/phpmyadmin:5.1
    container_name: phpmyadmin-bank
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: database-mysql
      MYSQL_ROOT_PASSWORD: 1234
      UPLOAD_LIMIT: 300M
    networks:
      - dev_network_bank

  phpmyadmin-connection-etc:
    image: phpmyadmin/phpmyadmin:5.1
    container_name: phpmyadmin-connection-etc
    restart: always
    ports:
      - "8084:80"
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    networks:
      - dev_network_bank
    
volumes:
  database-mysql:

networks:
  dev_network_bank:
    driver: bridge
